android: Fix createSurface compiler error
It looks like createSurface changed signature:

waffle/src/waffle/android/droid_surfaceflingerlink.cpp:113:36:
error: no matching function for call to
android::SurfaceComposerClient::createSurface(
  android::String8, int, const uint32_t&, const uint32_t&, android::<anonymous enum>, int)

Candidate is:
frameworks/native/include/gui/SurfaceComposerClient.h:80:24:
android::sp<android::SurfaceControl> android::SurfaceComposerClient::createSurface(
  const android::String8&, uint32_t, uint32 _t, android::PixelFormat, uint32_t)

Reviewed-by: Tom Gall <tom.gall@linaro.org>
Signed-off-by: Adrian Marius Negreanu <adrian.m.negreanu@intel.com>
Signed-off-by: Chad Versace <chad.versace@linux.intel.com>
(cherry picked from commit d49cc713332b565ad4913ef859972b82a3bca358)