tests/gl_basic_test: fix SURFACELESS_EGL only build
If the only platform selected is surfaceless_egl
test_gl_basic_glesX_fwdcompat is not defined which make compiler unhappy

--------------------------------------->8-------------------------------
.../gl_basic_test.c:581:24: error:
'test_gl_basic_gles2_fwdcompat' undeclared (first use in this function);
did you mean 'test_gl_basic_gles1_fwdcompat'?

unit_test_make(test_gl_basic_gles2_fwdcompat),
^
--------------------------------------->8-------------------------------

Not really sure to which extent fwdcompact is supported in
surfaceless_egl but an educated guess is it's pretty much the same as
for GBM.

Fixes: 19a126d ("tests/gl_basic_test: Support platform surfaceless_egl")
Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
[emil: keep the typo separate commit]
Signed-off-by: Emil Velikov <emil.velikov@collabora.com>